### ISSUE TITLE
Feature Request: Add ability to set a range for health / level when searching Beast collection

### ISSUE THREAD

**Issue by dfenland** [BibliothecaDAO/RealmsWorld#162]
### Describe the feature you'd like to request

For example, I want to display only Beasts that are +100 level and +300 health

### Describe the solution you'd like to see

A slider bar would be preferable, however an alternative could be to manually specify 'to/from' values

**Comment by Dprof-in-tech** [comment]
Hi @dfenland , i would love to work on this but please i need more information on this issue. Thank you

**Comment by dfenland** [comment]
> Hi @dfenland , i would love to work on this but please i need more information on this issue. Thank you

Hey see attached image which hopefully explains what I mean

![Screenshot1](https://github.com/BibliothecaDAO/RealmsWorld/assets/156480685/061e618e-c1c8-4e12-b379-0bd4207558c5)

**Comment by Dprof-in-tech** [comment]
i perfectly understand what you mean now.
so, could you please assign me to this issue? @dfenland

**Comment by RedBeardEth** [comment]
Hi @Dprof-in-tech - I have assigned you now (I had previously done some basic work on this which I have now pushed to the range-filter branch). 

![image](https://github.com/BibliothecaDAO/RealmsWorld/assets/90423049/96073b28-b062-4549-b893-a413ff37d389)

**Comment by Dprof-in-tech** [comment]
> Hi @Dprof-in-tech - I have assigned you now (I had previously done some basic work on this which I have now pushed to the range-filter branch).
> 
> ![image](https://private-user-images.githubusercontent.com/90423049/324291923-96073b28-b062-4549-b893-a413ff37d389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDMxMDYsIm5iZiI6MTcxMzc0MjgwNiwicGF0aCI6Ii85MDQyMzA0OS8zMjQyOTE5MjMtOTYwNzNiMjgtYjA2Mi00NTQ5LWI4OTMtYTQxM2ZmMzdkMzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIzNDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NGFmYWUwNjA4ZmM0ZmQ1NjA1ZTI0YmY2NWY5NmYwODFkNWQ2ZWVhMTdmODdjMzcyZmU2MzYxNDI4NzIzZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Or9TR3dM7HLycZfaBlt1-uXVp9GHWZgyx36mI0S5GNY)

okay chief. 
let me take a look at it and complete it

**Comment by Dprof-in-tech** [comment]
@RedBeardEth 
i'm having issues setting up this project on my local machine. i keep getting a database error.
Any clues as to how I can fix this so I can get on with fixing this issue

![image](https://github.com/BibliothecaDAO/RealmsWorld/assets/116242877/9006d673-1e95-4478-ae2e-9faae450fe21)

**Comment by Dprof-in-tech** [comment]
hello @RedBeardEth i've been waiting on your reply, I pulled the latest changes from main and tried setting up the project again on my local machine but I still get the same error when I'm trying to run the fronend nextjs app, what do we do about this?
